# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unknown_author_counter', models.IntegerField(default=0, verbose_name='Unknown author counter')),
                ('session_key', models.CharField(blank=True, max_length=200, verbose_name='Session key')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('anotation', models.TextField(blank=True, verbose_name='Anotation')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('has_question', models.BooleanField(default=False, verbose_name='Has question')),
                ('question', models.TextField(blank=True, verbose_name='Question')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('authors', models.ManyToManyField(blank=True, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='Authors')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_stories', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.CreateModel(
            name='StoryPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=200, verbose_name='Session key')),
                ('text', models.TextField(verbose_name='Text')),
                ('has_answer', models.BooleanField(default=False, verbose_name='Has answer')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is primary')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='story.StoryPart')),
                ('primary_story_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='story.StoryPart', verbose_name='Primary story line')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='story.Story', verbose_name='Story')),
            ],
            options={
                'verbose_name_plural': 'story parts',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='primary_story_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='story.StoryPart', verbose_name='Primary story line'),
        ),
    ]
