# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('anotation', models.TextField(blank=True, verbose_name='anotation')),
                ('is_finished', models.BooleanField(default=False, verbose_name='is finished')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('authors', models.ManyToManyField(blank=True, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='authors')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_stories', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.CreateModel(
            name='StoryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_lines', to='story.Story', verbose_name='story')),
            ],
            options={
                'verbose_name_plural': 'story lines',
            },
        ),
        migrations.CreateModel(
            name='StoryLinePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('story_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='story.StoryLine', verbose_name='story line')),
            ],
            options={
                'verbose_name_plural': 'story line parts',
                'ordering': ['story_line', 'story_part__level'],
            },
        ),
        migrations.CreateModel(
            name='StoryPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='story.StoryPart')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='story.Story', verbose_name='story')),
            ],
            options={
                'verbose_name_plural': 'story parts',
                'ordering': ['story', 'level'],
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', models.TextField(blank=True, verbose_name='diff')),
                ('text', models.TextField(verbose_name='text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='story.TextBlock')),
                ('story_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='story.StoryPart', verbose_name='story part')),
            ],
            options={
                'verbose_name_plural': 'text blocks',
            },
        ),
        migrations.AddField(
            model_name='storylinepart',
            name='story_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_parts', to='story.StoryPart', verbose_name='story part'),
        ),
        migrations.AddField(
            model_name='storylinepart',
            name='text_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_parts', to='story.TextBlock', verbose_name='text block'),
        ),
    ]
