# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storylinepart',
            options={'ordering': ['story_line', 'story_part__level'], 'verbose_name_plural': 'story line parts'},
        ),
        migrations.AlterModelOptions(
            name='storypart',
            options={'ordering': ['story', 'level'], 'verbose_name_plural': 'story parts'},
        ),
        migrations.RemoveField(
            model_name='storylinepart',
            name='parts',
        ),
        migrations.AlterField(
            model_name='storyline',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_lines', to='story.Story', verbose_name='story'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='diff',
            field=models.TextField(blank=True, verbose_name='diff'),
        ),
    ]
