# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=200, verbose_name='Session key')),
                ('text', models.TextField(verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='story.Story', verbose_name='Story')),
            ],
            options={
                'verbose_name_plural': 'etxt blocks',
            },
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='author',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='has_answer',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='session_key',
        ),
        migrations.AlterField(
            model_name='storypart',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='story.TextBlock', verbose_name='Text'),
        ),
    ]
