# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20160426_2105'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='storypart',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='storypart',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storypart',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='story.StoryPart'),
        ),
        migrations.AddField(
            model_name='storypart',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storypart',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storypart',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='story_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='story.StoryPart', verbose_name='story part'),
        ),
    ]
