# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20160408_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textblock',
            options={'verbose_name_plural': 'text blocks'},
        ),
        migrations.AddField(
            model_name='storypart',
            name='is_version',
            field=models.BooleanField(default=False, verbose_name='Is version'),
        ),
    ]
