# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0003_auto_20160418_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlockVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=200, verbose_name='Session key')),
                ('text', models.TextField(verbose_name='Text')),
                ('diff', models.TextField(verbose_name='Diff')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_versions', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('text_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='story.TextBlock', verbose_name='Text Block')),
            ],
            options={
                'verbose_name_plural': 'text block versions',
            },
        ),
        migrations.RenameField(
            model_name='storypart',
            old_name='text',
            new_name='text_block',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='is_version',
        ),
    ]
