# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20151119_2102'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='storypart',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='has_question',
            field=models.BooleanField(default=False, verbose_name='Has question'),
        ),
        migrations.AddField(
            model_name='story',
            name='question',
            field=models.TextField(blank=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='storypart',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='storypart',
            name='has_answer',
            field=models.BooleanField(default=False, verbose_name='Has answer'),
        ),
    ]
