# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20160419_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblockversion',
            name='text_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='story.TextBlock', verbose_name='Text Block'),
        ),
    ]
